name: ExamplePlugin
main: ExamplePlugin.MainClass
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: Kims
description: Example Plugin
commands:
  example:
    description: Example command
    usage: "/example"
    permission: exampleplugin.command.example
permissions:
  exampleplugin.command.example:
    description: "테스트 명령어"
    default: true